pipeline {
    agent any

    stages {
        stage('Stage 1') {
            steps {
                echo 'Hello World 1'
            }
        }
        stage('Stage 2') {
            steps {
                sh '''
                cd scripts
                sh shell-inq.sh
                sh if-then-else.sh
                sh file-check.sh
                # sh loop.sh
                sh function1.sh
                pwd
                '''
            }
        }
    }
}
