pipeline {
    agent any

    parameters {
        string(defaultValue: "feature-1", description: 'This is a parameter', name: 'BRANCH')
    }

    stages {
        stage('Getting code from GITHUB') {
            steps {
                echo 'Getting code from GITHUB'
                git 'https://github.com/sanjayrohilla13/bash-learning.git'
            }
        }
        stage('Build-stage') {
            steps {
                sh '''
                cd scripts
                sh shell-inq.sh
                sh if-then-else.sh
                sh file-check.sh
                # sh loop.sh
                sh function1.sh
                pwd
                echo ${BRANCH}
                '''
            }
        }
    }
}
